apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay
  namespace: quay
spec:
  configBundleSecret: quay-config-bundle
  components:
    - kind: objectstorage
      managed: false
    - kind: clair
      managed: true