apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
spec:
  components:
    pluginRegistry:
      openVSXRegistryURL: 'https://open-vsx.org/api'
    devWorkspace:
      storage:
        pvc:
          storageClass: "gp3-csi"