apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-devspaces
  namespace: openshift-devspaces
spec:
  channel: stable
  installPlanApproval: Automatic
  name: "devspaces"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"